spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk2.eho2z.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk2'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'Component responsible for user management created on Formation Expert BackEnd with teacher Valdir Cezar'
    version: '1.0.0'